name: Lint GO code

on:
  push:
    branches:
      - main
      # - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.1

    - name: Lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0
        # go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
        ls -la
        make lint    
