name: Test GO code

on:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [ubuntu-18.04]
        go-version: [1.14.x, 1.15.x]
    
    # defines the platform for each test run
    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: make build
      # run: |
      #   go build -v ./...
      #   ls -la
    
    - name: Test
      run: make tes
      # run: |
      #   go test -v ./...
