name: Test GO code

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    strategy:
      matrix:
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [ubuntu-20.04]
        # go-version: [1.17.x, 1.18.x]
        go-version: [1.17.1]
    
    # defines the platform for each test run
    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: make build
      # run: |
      #   go build -v ./...
      #   ls -la
    
    - name: Test
      run: make test

    - name: Code coverage
      run: make coverage
